# Generated by Django 3.1.4 on 2021-04-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='discountPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
    ]
