# Generated by Django 3.1.4 on 2021-04-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210410_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
