# Generated by Django 3.1.4 on 2021-04-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210410_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discountPrice',
        ),
    ]
