# Generated by Django 3.1.4 on 2021-04-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_discountprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discountPrice',
        ),
    ]
