# Generated by Django 3.1.4 on 2021-04-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_order_discountprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveredAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isDelivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
