# Generated by Django 3.1.4 on 2021-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210411_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
