# Generated by Django 3.1.4 on 2021-06-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
