export const REFUND_LIST_REQUEST = 'REFUND_LIST_REQUEST'
export const REFUND_LIST_SUCCESS = 'REFUND_LIST_SUCCESS'
export const REFUND_LIST_FAIL = 'REFUND_LIST_FAIL'
export const REFUND_LIST_RESET = 'REFUND_LIST_RESET'

export const REFUND_APPROVE_REQUEST = 'REFUND_APPROVE_REQUEST'
export const REFUND_APPROVE_SUCCESS = 'REFUND_APPROVE_SUCCESS'
export const REFUND_APPROVE_FAIL = 'REFUND_APPROVE_FAIL'
export const REFUND_APPROVE_RESET = 'REFUND_APPROVE_RESET'
