export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST'
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS'
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL'
export const REVIEW_LIST_RESET = 'REVIEW_LIST_RESET'

export const REVIEW_APPROVE_REQUEST = 'REVIEW_APPROVE_REQUEST'
export const REVIEW_APPROVE_SUCCESS = 'REVIEW_APPROVE_SUCCESS'
export const REVIEW_APPROVE_FAIL = 'REVIEW_APPROVE_FAIL'
export const REVIEW_APPROVE_RESET = 'REVIEW_APPROVE_RESET'