products = [
  {
    '_id': '1',
    'name': 'Mustard Sweatshirt',
    'image': '/images/sweat_yellow.jpeg',
    'description':
      'Unisex',
    'brand': 'SUMED',
    'category': 'Clothing',
    'price': 90.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Purple Sweatshirt',
    'image': '/images/sweat_purple.jpg',
    'description':
      'Unisex',
    'brand': 'SUMED',
    'category': 'Clothing',
    'price': 90.00,
    'countInStock': 0,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Red Sweatshirt',
    'image': '/images/sweat_red.jpg',
    'description':
      'Unisex',
    'brand': 'SUMED',
    'category': 'Clothing',
    'price': 115.00,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Green Sweatsirt',
    'image': '/images/sweat_green.jpeg',
    'description':
      'Material: 100% Cotton',
    'brand': 'SUMED',
    'category': 'Clothing',
    'price': 90.00,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Black Sweater',
    'image': '/images/polar.jpg',
    'description':
      '',
    'brand': 'SUMED',
    'category': 'Clothing',
    'price': 90.00,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Red T-Shirt',
    'image': '/images/tshirt_red.jpg',
    'description':
      'V-Neck Cotton',
    'brand': 'SUMED',
    'category': 'Clothing',
    'price': 35.00,
    'countInStock': 6,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '7',
    'name': 'Grey Sweatshirt',
    'image': '/images/sweat_grey.jpg',
    'description':
      'V-Neck Cotton',
    'brand': 'SUMED',
    'category': 'Clothing',
    'price': 90.00,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 8,
  },
  {
    '_id': '8',
    'name': 'Umbrella',
    'image': '/images/umbrella.jpg',
    'description':
      'Blue',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 90.00,
    'countInStock': 0,
    'rating': 1,
    'numReviews': 1,
  },
  {
    '_id': '9',
    'name': 'Usb Stick',
    'image': '/images/usb.jpg',
    'description':
      '8 GB',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 35.00,
    'countInStock': 2,
    'rating': 4,
    'numReviews': 3,
  },
  {
    '_id': '10',
    'name': 'Pen',
    'image': '/images/pen.jpg',
    'description':
      '',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 5.00,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 2,
  },
  {
    '_id': '11',
    'name': 'Pencil',
    'image': '/images/pencil.jpg',
    'description':
      '',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 3.00,
    'countInStock': 4,
    'rating': 3,
    'numReviews': 6,
  },
  {
    '_id': '11',
    'name': 'Backpack',
    'image': '/images/bag.jpg',
    'description':
      '',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 90.00,
    'countInStock': 6,
    'rating': 4,
    'numReviews': 9,
  },
  {
    '_id': '12',
    'name': 'Corkscrew',
    'image': '/images/tirbus.jpg',
    'description':
      '',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 10.00,
    'countInStock': 3,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '13',
    'name': 'Teddy Bear',
    'image': '/images/bear.jpg',
    'description':
      '',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 5.00,
    'countInStock': 5,
    'rating': 5,
    'numReviews': 13,
  },
  {
    '_id': '14',
    'name': 'Keychain',
    'image': '/images/anahtarlik.jpg',
    'description':
      '',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 5.00,
    'countInStock': 5,
    'rating': 2,
    'numReviews': 3,
  },
  {
    '_id': '15',
    'name': 'Notepad',
    'image': '/images/bloknot.jpg',
    'description':
      'A5 Blocknote',
    'brand': 'SUMED',
    'category': 'Other',
    'price': 10.00,
    'countInStock': 5,
    'rating': 4,
    'numReviews': 12,
  },
]
